# Generated by Django 3.1 on 2024-01-11 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20240101_1212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='User_name',
            new_name='user_name',
        ),
    ]
