# Generated by Django 3.1 on 2024-01-18 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20240102_2043'),
        ('accounts', '0010_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Products',
        ),
    ]
