# Generated by Django 3.1 on 2024-01-18 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20240118_1027'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
