# Generated by Django 3.1 on 2024-01-25 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0013_costumuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CostumUser',
            new_name='CustomUser',
        ),
    ]
